/* The following code was generated by JFlex 1.6.1 */

/* User code */
import java.io.*;
import java.util.*;


class CMinusTest {

	public static void main(String[] args) throws IOException {
		/* Test the program here */		
        if(args.length == 0){
            System.out.println("USAGE: java CMinusLex input_file [input_file]");
            System.exit(1);
        }
		
        boolean hasError = false;

        for (String filename : args) {


            Scanner manual = new CMinusScanner(filename);
            ArrayList<Token> manToks = new ArrayList<>();

            Token curToken = manual.getNextToken();

            while (curToken.getType() != Token.TokenType.EOF
                    && curToken.getType() != Token.TokenType.ERROR) {
                
                manToks.add(curToken);
                curToken = manual.getNextToken();
            }


            Scanner jflex  = new CMinusLex(filename);
            ArrayList<Token> lexToks = new ArrayList<>();

            curToken = jflex.getNextToken();

            while (curToken.getType() != Token.TokenType.EOF
                    && curToken.getType() != Token.TokenType.ERROR) {
                
                lexToks.add(curToken);
                curToken = jflex.getNextToken();
            }

            if (manToks.size() == lexToks.size()) {
                
                for (int i = 0; i < manToks.size(); ++i) {
                    Token man = manToks.get(i);
                    Token lex = lexToks.get(i);

                    if (man.getType() != lex.getType()) {
                        hasError = true;
                        System.out.println("Error in " + filename);
                        System.out.println("Mismatched token types.");
                        System.out.println("manual: " + man.getType());
                        System.out.println("jflex:  " + lex.getType() + '\n');
                    }
                }
            } else {
                hasError = true;
                System.out.println("Error in " + filename);
                System.out.println("Different token counts.");
            }
        }

        if (!hasError) {
            System.out.println("Success! Both lexers agreed.");
        } else {
            System.out.println("Lexing finished with errors.");
        }
	}

}
